spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: create
        default_schema: geo-information
